# Generated by Django 6.0.1 on 2026-01-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerlead',
            options={'ordering': ['services'], 'verbose_name': 'Registro de Lead', 'verbose_name_plural': 'Registros de Leads'},
        ),
    ]
